name: corner_shop_ml_env
dependencies:
  - pip=21.2.4
  - pip:
    - seaborn==0.12.1
    - imblearn==0.0
    - python-decouple==3.6
    - SQLAlchemy==1.4.44
    - ipykernel==6.16.2
    - google-api-python-client==2.64.0
    - google.cloud==0.34.0
    - google-cloud-bigquery==3.4.1
    - imbalanced-learn==0.6.0
    - db-dtypes==1.0.5
    - Flask==2.1.0
    - gunicorn==20.1.0